export const tableData = [
  {
    id: 0,
    schoolName: 'Saint Code',
    price: '120 000 (132 000) 100%/возможна помесячная оплата — очный формат\n'
        + '65 000 (71 500) 100%/возможна помесячная оплата — онлайн формат',
    hoursWithTeacher: '420+ неделя для составление резюме, портфолио и тренинги перед собеседованиями.',
    practiceHours: '240',
    programDuration: '13 недель - офлайн\\онлайн',
    pricePerHour: 'от 160 рублей до  320 рублей',
    programQuality: 'Не будем оценивать себя, так как это странно. Можете поговорить с нашими выпускниками. Их контакты будут в разделе историй студентов на этом сайте. ',
    supportAfter: 'Возможность сделать реальный коммерческий проект вместе с наставником. Такой фишки пока нет ни у одной школы программирования в России. \n'
        + 'Плюс мы продолжаем общаться с выпускниками и помогаем им с поиском работы, а также подготовкой к собеседованиям.  ',
    groupSize: 'до 12 человек',
    hoursWithRecording: 'нет',
    additionalInfo: '---',
    teacherSupportTime: 'Максимально быстрая, так как вы общаетесь вживую. В чате так же скорость ответа в среднем 15 минут',
  },
  {
    id: 1,
    schoolName: 'Эльбрус',
    price: '210 000 (228 000) = 100%/возможна помесячная оплата',
    hoursWithTeacher: '420+ приглашенные спикеры и лекции + йога',
    practiceHours: '240',
    programDuration: '12 недель/15недель = оффланй\\онлайн',
    pricePerHour: '500 рублей/час',
    programQuality: 'Высочайшее)) Хоть ребята и наши прямые конкуренты, но мы готовы их хвалить, так как знаем, что качество у них на высоте. \n'
            + 'Я думаю, что у них самый высокий процент трудоустроенных среди школ в России. Хотя они немного лукавят, говоря про 93%. Это процент ребят, которые освоили целиком программу и сдали все экзамены, а так как экзамен приближен к реальному, то его сдают далеко не все. В итоге процент трудоустроенных выглядит столь высоким. А если взять тех кто изначально пришёл, то думаю этот процент будет в 2-3 раза ниже.   \n'
            + 'Из важных плюсов — это высокая зп после выпуска. ',
    supportAfter: 'Есть телеграмм канал с вакансиями от партнеров и HR. Вакансии с выскоми зп в том числе, есть открытые вечера и встречи выпускников. Если выпускник приводит нового ученика, то ему в подарок эйрподс))',
    groupSize: 'до 12 человек',
    hoursWithRecording: 'первые 3 недели ведь самостоятельная работа',
    additionalInfo: 'Сильные ребята, обучают fullstack разработке, чистого фронта-нет!\n'
            + 'Необходимо сдать экзамен перед поступлением.  \n'
            + 'В первые 3 недели не загруженный график обучения. \n'
            + 'если не получается\\не нравиться\\ не утсраивает обучение, то можно вернуть деньги',
    teacherSupportTime: 'Максимально быстрая, так как вы общаетесь вживую. Скорость ответа в их учебном чате нам неизвестна',

  },
  {
    id: 2,
    schoolName: 'Алгоритмика Front-end',
    price: '80000  руб. всего при оплате помесячно\n'
        + '75 000 руб. при оплате сразу',
    hoursWithTeacher: '256 часов',
    practiceHours: '140',
    programDuration: '8 месяцев \n'
        + 'пн и чт - по 2 часа\n'
        + 'сб - по 4 часа',
    pricePerHour: '290 руб\\час',
    programQuality: 'Неизвестно',
    supportAfter: 'Консультируют в течение 1-2 месяцев по резюме и готовят к прохождению собеседований',
    groupSize: '15-18 человек в онлайн группе',
    hoursWithRecording: 'нет',
    additionalInfo: 'Есть формат и буткемпа, но только в Москве, стоимость от 190к\\руб\n'
        + 'Eсть лицензия на образование, можно будет получить налоговый вычет.',
    teacherSupportTime: '---',

  },
  {
    id: 3,
    schoolName: 'Алгоритмика Bootcamp',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 4,
    schoolName: 'Яндекс.Практикум',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 5,
    schoolName: 'Geekbrains',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 6,
    schoolName: 'Skillbox',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 7,
    schoolName: 'Академия Шаг',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 8,
    schoolName: 'Школа БруноЯм',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 9,
    schoolName: 'ИТМО Системное и прикладное програмное обеспечение',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 10,
    schoolName: 'ИТМО Веб-разработка',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
  {
    id: 11,
    schoolName: 'Самостоятельное освоение',
    price: '',
    hoursWithTeacher: '',
    practiceHours: '',
    programDuration: '',
    pricePerHour: '',
    programQuality: '',
    supportAfter: '',
    groupSize: '',
    hoursWithRecording: '',
    additionalInfo: '',
    teacherSupportTime: '',

  },
]
